workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    artifacts:
      - app/build/outputs/**/*.aab
#    publishing:
#      email:
#        recipients:
#          - user_1@example.com
#          - user_2@example.com
#        notify:
#          success: true
#          failure: false
#      google_play:
#        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
#        track: internal
#        submit_as_draft: true